version: "3.8"

services:
  python-main-backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      FLASK_ENV: development
      MYSQL_HOST: dev-db
      MYSQL_DATABASE: test_db
      MYSQL_USER: root
      MYSQL_PASSWORD: my-secret-pw
      REDIS_HOST: redis
    ports:
      - "5005:5000"
    depends_on:
      - dev-db
      - redis
    volumes:
      - .:/app # 將當前目錄掛載到容器內的 /app 目錄
  voice-api-server:
    build:
      context: ./voiceapi
      dockerfile: Dockerfile
    environment:
      FLASK_ENV: development
    ports:
      - "5000:5000"

  dev-db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: test_db
    ports:
      - "3300:3306"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  adminer:
    image: adminer:latest
    ports:
      - "3002:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=dev-db
  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=redis
    ports:
      - 3003:8081
