# Generated by Django 5.1.2 on 2024-10-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAnalysis',
            fields=[
                ('image', models.TextField(primary_key=True, serialize=False)),
                ('human', models.FloatField()),
                ('artificial', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoAnalysis',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('status', models.TextField()),
                ('url', models.URLField()),
                ('progress', models.FloatField()),
                ('results', models.ManyToManyField(blank=True, to='video_detect.imageanalysis')),
            ],
        ),
    ]
